# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a55x/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),a55x)

$(call add-radio-file-sha1-checked,radio/fld.bin_SM-A556E,b31d9817cdb96d6214114f10d977a9a91af50d42)
$(call add-radio-file-sha1-checked,radio/harx.bin_SM-A556E,d872ed916acf56c82632cd28614bfafc1178f53b)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-A556E,5e510770e2d0f3f0fb68024e94c3ea87468e29ec)
$(call add-radio-file-sha1-checked,radio/ldfw.img_SM-A556E,e82b714ad95e72f6bf21e82b21d497af7612d3e2)
$(call add-radio-file-sha1-checked,radio/models,0f7c19fb391b6b0181f8d49f0cd6a65340cd10ec)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-A556E,1f7d34d220be9896a275c9c23f18529cb465208f)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-A556E,cfd3c1a40b51417667b8e4b1ef71fc71b7e476e0)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-A556E,6df30249d58e215bbb572c646065947aa8ba8811)
$(call add-radio-file-sha1-checked,radio/tzar.img_SM-A556E,6dd0d57184f75ac04fb6644c01ddbeb728205468)
$(call add-radio-file-sha1-checked,radio/tzsw.img_SM-A556E,203c9224b7cc1a8444152179630a02a38412b3e3)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-A556E,427f31b7c2e27d546c1d8b83497899bf87e99918)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-A556E,b1776216b2d67bf0ccd6c907e594a5033bbcd463)
$(call add-radio-file-sha1-checked,radio/version_SM-A556E,a12b2d4e5c4272dda3f5df2f0583f3dff8243cd8)

endif
